/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Smartphone;
import AssistanceTouristique.*;

import org.omg.CosNaming.NamingContext;
import org.omg.PortableServer.POA;
import org.omg.PortableServer.POAHelper;

/**
 *
 * @author Lydia
 */
public class ServeurSmartphone2 extends javax.swing.JFrame {

    public static String nomSmartphone="Smartphone";
    private String codeSite;
    private int idVisite;
    private float satisfaction = (float)50;
    
    public ServeurSmartphone2(int idVisite, String codeSite) {
        this.idVisite=idVisite;
        this.codeSite=codeSite;
        initComponents(); 
    }
    
    public void afficherInterfaceAvis() {
        new ServeurSmartphone2(this.idVisite, this.codeSite).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EcranAvis = new javax.swing.JPanel();
        jLabelAvisInteresse = new javax.swing.JLabel();
        jSliderSatisfaction = new javax.swing.JSlider();
        jButtonDonnerAvis = new javax.swing.JButton();
        jButtonIgnorer = new javax.swing.JButton();
        jLabelSatisfaction = new javax.swing.JLabel();
        jLabelMerciDeVotreVisite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelAvisInteresse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAvisInteresse.setText("Votre avis nous intéresse !");

        jSliderSatisfaction.setMaximum(4);
        jSliderSatisfaction.setToolTipText("");
        jSliderSatisfaction.setValue(2);
        jSliderSatisfaction.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderSatisfactionStateChanged(evt);
            }
        });

        jButtonDonnerAvis.setBackground(new java.awt.Color(0, 51, 255));
        jButtonDonnerAvis.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonDonnerAvis.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDonnerAvis.setText("Donner son avis !");
        jButtonDonnerAvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDonnerAvisActionPerformed(evt);
            }
        });

        jButtonIgnorer.setBackground(new java.awt.Color(0, 51, 255));
        jButtonIgnorer.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jButtonIgnorer.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIgnorer.setText("Ignorer");
        jButtonIgnorer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgnorerActionPerformed(evt);
            }
        });

        jLabelSatisfaction.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelSatisfaction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSatisfaction.setText("Moyen");

        jLabelMerciDeVotreVisite.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMerciDeVotreVisite.setForeground(new java.awt.Color(0, 51, 255));
        jLabelMerciDeVotreVisite.setText("Merci de votre visite !");

        javax.swing.GroupLayout EcranAvisLayout = new javax.swing.GroupLayout(EcranAvis);
        EcranAvis.setLayout(EcranAvisLayout);
        EcranAvisLayout.setHorizontalGroup(
            EcranAvisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranAvisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EcranAvisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSatisfaction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAvisInteresse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSliderSatisfaction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMerciDeVotreVisite, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EcranAvisLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(EcranAvisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonIgnorer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDonnerAvis, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                        .addGap(60, 60, 60)))
                .addContainerGap())
        );
        EcranAvisLayout.setVerticalGroup(
            EcranAvisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranAvisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMerciDeVotreVisite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabelAvisInteresse)
                .addGap(34, 34, 34)
                .addComponent(jSliderSatisfaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSatisfaction)
                .addGap(57, 57, 57)
                .addComponent(jButtonDonnerAvis, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIgnorer)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EcranAvis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EcranAvis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderSatisfactionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderSatisfactionStateChanged
        System.out.println(jSliderSatisfaction.getValue());
        //Maj du label en fonction de la valeur
        switch (jSliderSatisfaction.getValue()) {
            case 0:
            jLabelSatisfaction.setText("Très insatisfait");
            satisfaction = (float) 0;
            break;
            case 1:
            jLabelSatisfaction.setText("Insatisfait");
            satisfaction = (float) 25;
            break;
            case 2:
            jLabelSatisfaction.setText("Moyen");
            satisfaction = (float) 50;
            break;
            case 3:
            jLabelSatisfaction.setText("Satisfait");
            satisfaction = (float) 75;
            break;
            case 4:
            jLabelSatisfaction.setText("Très satisfait");
            satisfaction = (float) 100;
            break;
        }
    }//GEN-LAST:event_jSliderSatisfactionStateChanged

    private void jButtonDonnerAvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDonnerAvisActionPerformed
        try {
            /*********** Recherche du service ES du site ************/
            String nomServES = "ES " + this.codeSite;
            
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init(new String[0],null);
            
            NamingContext nameRoot=org.omg.CosNaming.NamingContextHelper.narrow(orb.resolve_initial_references("NameService"));

            org.omg.CosNaming.NameComponent[] nameToFind = new org.omg.CosNaming.NameComponent[1];
            nameToFind[0] = new org.omg.CosNaming.NameComponent(nomServES, "");
            org.omg.CORBA.Object distantServES = nameRoot.resolve(nameToFind);
               
             ServiceESSite servES = ServiceESSiteHelper.narrow(distantServES);

            servES.donnerAvisVisite(this.idVisite, this.satisfaction);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        //on quitte le programme
        System.exit(0);
    }//GEN-LAST:event_jButtonDonnerAvisActionPerformed

    private void jButtonIgnorerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgnorerActionPerformed
        //on quitte le programme
        System.exit(0);
    }//GEN-LAST:event_jButtonIgnorerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServeurSmartphone2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServeurSmartphone2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServeurSmartphone2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServeurSmartphone2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
           org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init(args,null);

            // Gestion du POA
             //****************
             // Recuperation du POA
            POA rootPOA = POAHelper.narrow(orb.resolve_initial_references("RootPOA"));

            // Creation du servant
            //*********************
           SmartphoneTouristeImpl monSmartphone = new SmartphoneTouristeImpl();

            // Activer le servant au sein du POA et recuperer son ID
            byte[] monSmartphoneId = rootPOA.activate_object(monSmartphone);

            // Activer le POA manager
            rootPOA.the_POAManager().activate();

            /******** Enregistrement dans le service de nommage ********/
         
            // Recuperation du naming service
            NamingContext nameRoot=org.omg.CosNaming.NamingContextHelper.narrow(orb.resolve_initial_references("NameService"));

            // Construction du nom a enregistrer
            org.omg.CosNaming.NameComponent[] nameToRegister = new org.omg.CosNaming.NameComponent[1];
            nameToRegister[0] = new org.omg.CosNaming.NameComponent(nomSmartphone,"");

            // Enregistrement de l'objet CORBA dans le service de noms
            nameRoot.rebind(nameToRegister,rootPOA.servant_to_reference(monSmartphone));
            System.out.println("==> Nom '"+ nomSmartphone + "' est enregistre dans le service de noms.");

            String IORServant = orb.object_to_string(rootPOA.servant_to_reference(monSmartphone));
            System.out.println("L'objet possede la reference suivante :");
            System.out.println(IORServant);
            
            // Lancement de l'ORB et mise en attente de requete
            //**************************************************
            orb.run();

        }
        catch(Exception e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServeurSmartphone2().setVisible(true);
            }
        });*/
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EcranAvis;
    private javax.swing.JButton jButtonDonnerAvis;
    private javax.swing.JButton jButtonIgnorer;
    private javax.swing.JLabel jLabelAvisInteresse;
    private javax.swing.JLabel jLabelMerciDeVotreVisite;
    private javax.swing.JLabel jLabelSatisfaction;
    private javax.swing.JSlider jSliderSatisfaction;
    // End of variables declaration//GEN-END:variables
}
